# These are the configuration options available to the user in the UI on the Service page, under 'Config.'
# See github.com/Start9Labs/lnd-wrapper for a good example config_spec

{}

when
type: pointer
# interface is the interface in the dependecy's package that you want to connect to - ie control in lnd
interface: _